### ISSUE TITLE
Post message no long works?

### ISSUE THREAD

**Issue by RedHaze** [SuperSpyTX/Hack-Yak#2]
Using the parameters given, postMessage.php always returns a "2." Perhaps a new parameter was introduced?

Reproduce by using your python script and uncommenting lines 153-156.

**Comment by gregory791** [comment]
@soren121 could you provide more info about how the key is generated on Android? Read somewhere that the iOS key is still static, if so do you know what it is? Had a look through your js code, and literally matched it with pyak but getting 401s all the time. Thanks

**Comment by GHowlett** [comment]
@durtySherpa Requesting that you add 'g-howl'

**Comment by LiamBui** [comment]
@durtySherpa hi could you add me as well? /u/leeyum 
Much appreciated :)

**Comment by fresh83** [comment]
has anyone actually been added to this shit?


—

**Comment by soren121** [comment]
@fresh83 durtySherpa bailed, so no.

**Comment by fresh83** [comment]
@soren121  did u get locked out td at noon too?

**Comment by fresh83** [comment]
Starting at noon today the endpoint :https://us-east-api.yikyakapi.net/api/yaks stopped working for me ...anyone have the same issue and if so plz post if u find a solution

**Comment by sudofox** [comment]
Same here, it's not working
I'll try running my phone through fiddler later to see what does work

**Comment by soren121** [comment]
@fresh83 My app still works, although it doesn't yet use the /yaks method.

**Comment by fresh83** [comment]
maybe i just need a new endpoint to use and that old one is depreciated idk


—

**Comment by soren121** [comment]
@fresh83 No, the endpoint is fine. I suspect the issue is that they finally removed the old API key from their service, especially given that it stopped working at noon. The newer Android API key is on /r/yakattack. (I added you, by the way. I'm a mod there now.)

**Comment by fresh83** [comment]
Have I told you I love you yet td? Bc I do lol Thanks man


—

**Comment by juanfausd** [comment]
Hi guys! Can anyone send me the new API key? I'm developing YikYakDotNet API for free and just wanted to update it. Thanks in advance!

**Comment by SuperSpyTX** [comment]
Made a subreddit.  I'll try to add all the members that I can see here.
Anyone who wants in, should post now.

**Comment by fresh83** [comment]
add me  : uknowchuck 


—

**Comment by rondaa** [comment]
Add me too please: corporat

**Comment by fresh83** [comment]
Does anybody here work in PHP and/or have a easy way to generate user_id’s in php?


—

**Comment by bamasmith** [comment]
Add me in the subreddit please: bamasmith

**Comment by GHowlett** [comment]
@SuperSpyTX Go ahead and add 'g-howl' too

**Comment by Radiati0n** [comment]
Did you make another subreddit? Because we've had one for quite a while now.

**Comment by fresh83** [comment]
What is wrong with this request URL :

https://us-east-api.yikyakapi.net/api/getMessages?lat=42.6727&long=-83.2158&userID=7E9C1AA06DEEED6BDE84B5619631EDD8&userLong=-83.2158&userLat=42.6727&salt=1423960096&hash=NzVkYmExYTVkZGNjYjFkMmZiOTVhYmVhMDc1NTM1Mjk0YTNiMGJkZQ==    ?  been trying for hours. Cant get anywhere. I must be missing or doing something wrong. My system stopped abruptly about 2 days ago @7:12PM eastern


—

**Comment by sudofox** [comment]
Make sure you have "Android" in your user agent


On Sat, Feb 14, 2015 at 7:31 PM, fresh83 <notifications@github.com> wrote:

> What is wrong with this request URL :
>
>
> https://us-east-api.yikyakapi.net/api/getMessages?lat=42.6727&long=-83.2158&userID=7E9C1AA06DEEED6BDE84B5619631EDD8&userLong=-83.2158&userLat=42.6727&salt=1423960096&hash=NzVkYmExYTVkZGNjYjFkMmZiOTVhYmVhMDc1NTM1Mjk0YTNiMGJkZQ==
>   ?  been trying for hours. Cant get anywhere. I must be missing or doing
> something wrong. My system stopped abruptly about 2 days ago @7:12PM eastern
>
>
> —
> Sent from Mailbox
>
> On Fri, Feb 13, 2015 at 9:15 PM, Radiati0n <notifications@github.com>
> wrote:
>
> > Did you make another subreddit? Because we've had one for quite a while
> now.
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/SuperSpyTX/Hack-Yak/issues/2#issuecomment-74357148
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SuperSpyTX/Hack-Yak/issues/2#issuecomment-74398440>.
>



-- 
Hello, my name is Austin Burk
About Sudomemo, my project to remake Flipnote Hatena:
http://www.sudomemo.net

**Comment by seniordoodle** [comment]
@SuperSpyTX I'd be stoked to be added to the subreddit -- "seniordoodle".

**Comment by SuperSpyTX** [comment]
@Radiati0n I assumed the old one was dead considering it was long ago when I requested to be added to it.  Hence why I started another.

**Comment by Radiati0n** [comment]
@SuperSpyTX I'm pretty sure I added you. Lots of info on there. I would suggest we keep everything in one place.

**Comment by SuperSpyTX** [comment]
Heh! Well alright then I'll close my other subreddit.

**Comment by Radiati0n** [comment]
Great. I just want to make it easier for us to collaborate by keeping it all together and somewhat organized.

**Comment by sudofox** [comment]
Can you add /u/sudofox? Thanks

**Comment by juanfausd** [comment]
Add me in the subreddit please: juanfausd. Thanks!

**Comment by johnjreiser** [comment]
Could I also be added? /u/johnjreiser

**Comment by Bradley-Plus** [comment]
Proposal to move further conversations to other (specific) issue threads and/or Reddit entirely.

**Comment by soren121** [comment]
Agreed. @SuperSpyTX, what do you think about locking this issue?

Sent from my Windows Phone

-----Original Message-----

**Comment by fresh83** [comment]
All this github issue convo should be archived(as in posted to the subredit) and then deleted  …. you know its just a matter of time ….if it has not happened already,  that one of their devs is going to reverse engineer shit back to this lib( it is the top result for “Hack Yak” on google , ask to join the subredit and then make all our lives hell. 


—

**Comment by SuperSpyTX** [comment]
Yeah was thinking.  This conversation should go over to a subreddit, or a "forum" per se.

If you need to get on the subreddit, please contact @soren121 or I over reddit.
/u/SuperSpyTX
/u/soren121

I do want to end this though, with a small "bang" if you will.

I've never really created a successful community (even though it wasn't an intention of mine) and I was quite surprised how big this issue has got.

If anyone here would like to help update this repository, let me know!  Otherwise I will now lock one of the biggest issues on GitHub :'(
